### ISSUE TITLE
Unable to run geoip:update (Out of memory error)

### ISSUE THREAD

**Issue by kyranb** [pulkitjalan/geoip#16]
Using version 2.2.2 of this package on L5.2, when running the artisan command `geoip:update` I'm getting 'Cannot allocate memory' issues. (With 500mb of free ram) and a ascii is printed out to the console like so:

```
��h��h��h��h��h��h��h��h��h��h��h��h��h��h��h��h��h��h�� h��!h��"h��#h��$h��%h��&h��'h��(h��)h��*h��+h��,h��-h��.h��/h��0h��1h��2h��35�~4h��5h��6h��7h��8h��9h��:h��;h��<h��=h��>h��?h��@h��Ah��Bh��Ch��Dh��Eh��Fh��Gh��Hh��Ih��Jh��Kh��Lh��Mh��Nh��Oh��Ph��Q5�oRh��Sh��Th��Uh��Vh��Wh��Xh��Yh��Zh��[h��\h��]h��^h��_h��`h��a$S�b'kchd�se��f��g�h��hi j
```

See the stacktrace below:

```
mmap() failed: [12] Cannot allocate memory
PHP Fatal error:  Out of memory (allocated 88670208) (tried to allocate 76079136 bytes) in /home/forge/app/vendor/pulkitjalan/geoip/src/GeoIPUpdater.php on line 86

PHP Fatal error:  Uncaught ErrorException: proc_open(): fork failed - Cannot allocate memory in /home/forge/app/vendor/symfony/console/Application.php:898
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'proc_open(): fo...', '/home/forge/zen...', 898, Array)
#1 /home/forge/app/vendor/symfony/console/Application.php(898): proc_open('stty -a | grep ...', Array, NULL, NULL, NULL, Array)
#2 /home/forge/app/vendor/symfony/console/Application.php(701): Symfony\Component\Console\Application->getSttyColumns()
#3 /home/forge/app/vendor/symfony/console/Application.php(662): Symfony\Component\Console\Application->getTerminalDimensions()
#4 /home/forge/app/vendor/symfony/console/Application.php(595): Symfony\Component\Console\Application->getTerminalWidth()
#5 /home/forge/app/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(141): Symfony\Component\Console\Application->renderException(Object(Symfony\Component\Debug\Excep in /home/forge/app/vendor/symfony/console/Application.php on line 898
```

Previously it worked fine and I don't recall making any changes that would have affected this. Has anyone else seen the same issue or have any ideas how to resolve it?

Thanks!

**Comment by andreasba** [comment]
I can second this @kyranb , a lot of gibberish

**Comment by pulkitjalan** [comment]
fixed in version 2.3.0

**Comment by ebisbe** [comment]
It's happening to me still when I composer install

```
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 53480624 bytes) in /Users/enricu/Development/bikebitants/test/vendor/pulkitjalan/geoip/src/GeoIPUpdater.php on line 62
PHP Stack trace:
PHP   1. {main}() /Users/enricu/Development/bikebitants/test/artisan:0
PHP   2. Illuminate\Foundation\Console\Kernel->handle() /Users/enricu/Development/bikebitants/test/artisan:35
PHP   3. Symfony\Component\Console\Application->run() /Users/enricu/Development/bikebitants/test/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:123
PHP   4. Symfony\Component\Console\Application->doRun() /Users/enricu/Development/bikebitants/test/vendor/symfony/console/Application.php:121
PHP   5. Symfony\Component\Console\Application->doRunCommand() /Users/enricu/Development/bikebitants/test/vendor/symfony/console/Application.php:190
PHP   6. Illuminate\Console\Command->run() /Users/enricu/Development/bikebitants/test/vendor/symfony/console/Application.php:826
PHP   7. Symfony\Component\Console\Command\Command->run() /Users/enricu/Development/bikebitants/test/vendor/laravel/framework/src/Illuminate/Console/Command.php:167
PHP   8. Illuminate\Console\Command->execute() /Users/enricu/Development/bikebitants/test/vendor/symfony/console/Command/Command.php:262
PHP   9. Illuminate\Container\Container->call() /Users/enricu/Development/bikebitants/test/vendor/laravel/framework/src/Illuminate/Console/Command.php:182
PHP  10. Illuminate\Container\BoundMethod::call() /Users/enricu/Development/bikebitants/test/vendor/laravel/framework/src/Illuminate/Container/Container.php:531
PHP  11. Illuminate\Container\BoundMethod::callBoundMethod() /Users/enricu/Development/bikebitants/test/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31
PHP  12. Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() /Users/enricu/Development/bikebitants/test/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87
PHP  13. call_user_func_array:{/Users/enricu/Development/bikebitants/test/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29}() /Users/enricu/Development/bikebitants/test/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
PHP  14. PulkitJalan\GeoIP\Console\UpdateCommand->fire() /Users/enricu/Development/bikebitants/test/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
PHP  15. PulkitJalan\GeoIP\GeoIPUpdater->update() /Users/enricu/Development/bikebitants/test/vendor/pulkitjalan/geoip/src/Console/UpdateCommand.php:46
PHP  16. PulkitJalan\GeoIP\GeoIPUpdater->updateMaxmindDatabase() /Users/enricu/Development/bikebitants/test/vendor/pulkitjalan/geoip/src/GeoIPUpdater.php:38
PHP  17. gzdecode() /Users/enricu/Development/bikebitants/test/vendor/pulkitjalan/geoip/src/GeoIPUpdater.php:62


  [Symfony\Component\Debug\Exception\FatalErrorException]
  Allowed memory size of 134217728 bytes exhausted (tried to allocate 5348062
  4 bytes)
```

**Comment by Tankonyako** [comment]
have same
